# RFContainers plugin by Rifle D. Luffy
# Version 1.0
# #=============[Container Attributes]=============##
# max-pile-size: The size that each slot of a single item can contain.
# max-size: The maximum amount of slots each container has. Must be in multiples of 9
max-pile-size: 4096
max-size: 18