# Rifle's Chair plugin by Rifle D. Luffy
# Version 1.0
# #=============[When Damaged By an Entity]=============##
# toss-player-on-damage: Should it eject players of their seats when damaged?
# minimum-toss-damage: The minumum damage needed to toss a player out of their seat
toss-player-on-damage: false
minimum-toss-damage: 2